include_recipe "vagrant_main::npm_packages"
include_recipe "vagrant_main::apt_packages"
include_recipe "vagrant_main::php"
include_recipe "vagrant_main::composer"
include_recipe "vagrant_main::phpunit"
include_recipe "vagrant_main::distribute"
include_recipe "vagrant_main::ruby_gems"
include_recipe "vagrant_main::heroku_toolbelt"
