include_recipe "vagrant-main::php"
include_recipe "vagrant-main::phpunit"
include_recipe "vagrant-main::distribute"
include_recipe "vagrant-main::ruby_gems"
include_recipe "vagrant-main::npm_packages"
include_recipe "vagrant-main::apt_packages"
include_recipe "vagrant-main::heroku_toolbelt"
